voltdb:
  nodes:
#  - host: voltdb1-database-neon.marathon
#    port: 21212
#    marathonAppId: neon/database/voltdb1
#  - host: voltdb2-database-neon.marathon
#    port: 21212
#    marathonAppId: neon/database/voltdb2
  - host: 1-voltdb-infra-neon.marathon
    port: 21212
    marathonAppId: neon/infra/voltdb/1

  
marathon:
  resolve: true
  host:
    url: http://192.168.14.21:8080
    
    
partitionToUse: 2

bcCountPerPartition: 10

subscriberCount: 500000

startMsisdn: 919200000000


---
spring:
  profiles: messaging

